# Generated by Django 2.2.dev20181207183237 on 2018-12-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=25)),
                ('informacoes_adicionais', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('data_inicial', models.DateField(null=True)),
                ('data_final', models.DateField(null=True)),
                ('orcado', models.DecimalField(decimal_places=2, max_digits=128)),
                ('informacoes_adicionais', models.TextField(null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='obras.Empresa')),
            ],
        ),
    ]
