# Generated by Django 2.2.dev20181207183237 on 2018-12-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='razao_social_sem_acento',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
