# Generated by Django 2.2.dev20181207183237 on 2018-12-08 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Esclarecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(null=True)),
                ('gps_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('data_criado', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Não tem novidades'), (2, 'Deram andamento'), (3, 'Finalizado')], null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='obras.Obra')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='fotos/')),
                ('data_criado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto_Esclarecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(null=True)),
                ('esclarecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='esclarecimento.Esclarecimento')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='esclarecimento.Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(null=True)),
                ('data_criado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('esclarecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='esclarecimento.Esclarecimento')),
            ],
        ),
    ]
