# Generated by Django 2.2.dev20181207183237 on 2018-12-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esclarecimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esclarecimento',
            name='gps_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='esclarecimento',
            name='gps_long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
